### ISSUE TITLE
Login autofill doesn't work in Firefox

### ISSUE THREAD

**Issue by EvanOxfeld** [tbosch/autofill-event#5]
The login form manual test cases fail for me in Firefox 26.0 in both Windows and Linux. Let me know if there's any additional info that could help with debugging.

Btw, thanks for this polyfill @tbosch!

**Comment by tbosch** [comment]
Just double checked, and it works for me.
What error messages are you getting? You should only see the following, as Firefox does not support those. However, the 3rd test should be good.
- "Error: browser does not support auto filling username/password on load"
- "Error: browser does not support auto clearing of passwords"

**Comment by EvanOxfeld** [comment]
Ah, I didn't realize Firefox doesn't support those. Only the `auto fills password if the username is filled later on` spec passes in FF. As that's expected, I'm closing this defect.

Thanks again @tbosch!
