### ISSUE TITLE
Firefox: Auto fill does not trigger on view changed

### ISSUE THREAD

**Issue by gaoht** [tbosch/autofill-event#7]
My Firefox version: 26.0
This is my test sample:
http://plnkr.co/edit/wZHXw4PCWolrDoTMw8nZ?p=preview

I copied the autofill-event.js to the plunkr for test.

There are 2 errors:
- When document ready, triggered "DOMContentLoaded" , 200ms delay to trigger change event is not longer enough(I set the delay in the sample to 500ms works fine)
- When I turn to index(another view), then back to sign in view, browser auto fills the inputs, but the event not trigger. I found that auofill is not checked when ui-view changed, so I tried to manually trigger autofill check in the controller, as: $rootElement.find('input').checkAndTriggerAutoFillEvent() also failed.

Is anything wrong in my code?

**Comment by tbosch** [comment]
Hi,
sorry for the late answer.
Yes, calling `$rootElement.find('input').checkAndTriggerAutoFillEvent()` manually should auto fill the values, if the view is connected to the root element.

Will try to reproduce this and then come back to you.

**Comment by tbosch** [comment]
Hi, here is an updated plunker: http://plnkr.co/edit/AWSlgcPHMFVCMxhuajDo?p=preview

Just need to wait a little bit before calling `changeAndTriggerAutoFillEvent()` (I used 200ms in the example).

Ok, I see the problem now. This polyfill should automatically call `changeAndTriggerAutoFillEvent` if Angular is present and we are doing view changes.

Would you like to try a PR for this?

**Comment by gaoht** [comment]
@tbosch, Thanks very much, that works now.
