### ISSUE TITLE
changing values in Angular scope

### ISSUE THREAD

**Issue by alexarsh** [tbosch/autofill-event#8]
My stack is Django+Angular. I have login form with username and password.
Autofill is not changing my values in Angular scope in firefox 26.0.
I tried to do:

element.find('input[name="username"]').checkAndTriggerAutoFillEvent();
element.find('input[name="password"]').checkAndTriggerAutoFillEvent();
scope.init(); //just emptying the values

and it fixes the password field, but not the username field and I can't understand what the problem is. 

Thanks, Alex A.

**Comment by tbosch** [comment]
Hi,
can you create a sample page that shows the problem?
See e.g. https://github.com/tbosch/autofill-event/blob/master/test/manual/login-form.html

Yes, calling `checkAndTriggerAutoFillEvent` manually should solve the problem...

**Comment by tbosch** [comment]
Closing this. Please create a new issue if you have a sample page...
