### ISSUE TITLE
Error in IE8

### ISSUE THREAD

**Issue by joshbmarshall** [tbosch/autofill-event#9]
IE8 can't use addEventListener, so it produces an error message

I fixed it locally using http://stackoverflow.com/questions/9769868/addeventlistener-not-working-in-ie8

**Comment by dmatheron** [comment]
+1 got the same issue in IE8

**Comment by tbosch** [comment]
This won't work in IE8, sorry, as it uses capturing event listeners for the `blur` event. Capturing event listeners (calling `addEventListener` with the last value set to `true`) are not supported in IE8 as far as I know (the normal `attachEvent` is just a bubbling event listener...)

**Comment by tbosch** [comment]
But maybe we don't need to listen for `blur` events in IE8, then it could work. Sorry, don't have IE8 here...

**Comment by joshbmarshall** [comment]
## The work around I posted earlier is working well for me in production on a number of sites

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by KimGressens** [comment]
The workaround you posted isn't working for me.

To be complete : the workaround I tested was shimming the addEventListener call in IE8 . The result was that changes from the password manager were still not detected.

**Comment by AdamQuadmon** [comment]
I opened a PR for that

https://github.com/tbosch/autofill-event/pull/13

**Comment by jca258** [comment]
This was solved with pull request #18

**Comment by tbosch** [comment]
Closing this as #18 is merged.
